openapi: '3.0.3'
info:
  title: Booking API For CMS
  version: '1.0'
servers:
  - url: https://localhost:3000/api
    description: Local server

components:
  schemas:
    timeRange:
      type: object
      properties:
        start:
          type: string
          format: time
          example: '09:00'
          description: Start time
        end:
          type: string
          format: time
          example: '18:00'
          description: End time
    workHoursOfDays:
      type: object
      properties:
        monday:
          type: array
          items:
            $ref: '#/components/schemas/timeRange'
        tuesday:
          type: array
          items:
            $ref: '#/components/schemas/timeRange'
        wednesday:
          type: array
          items:
            $ref: '#/components/schemas/timeRange'
        thursday:
          type: array
          items:
            $ref: '#/components/schemas/timeRange'
        friday:
          type: array
          items:
            $ref: '#/components/schemas/timeRange'
        saturday:
          type: array
          items:
            $ref: '#/components/schemas/timeRange'
        sunday:
          type: array
          items:
            $ref: '#/components/schemas/timeRange'
        
paths:
  /stores/{id}/workHours:
    get:
      description: 'Get work hours for a store'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the store
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workHoursOfDays'
        '404':
          description: Not Found


                    
 